.babelrc
.gitignore
client/components/GithubUpdates.js
client/components/collab.js
client/components/navbar.js

Added title, added semantic to .gitignore file
---

Collab page

---

client/components/auth-form.js
package-lock.json
package.json
server/auth/github.js
server/auth/index.js
server/db/models/user.js

GitHub login is working and connects to our GitHub app.

add login with github

---

client/components/chatbox.js
client/components/chatboxContainer.js
client/store/chatbox.js
script/seed.js
server/api/chatroom.js
server/db/models/chatroom.js
server/db/models/index.js
server/db/models/message.js

Chat is functioning now and is persistent

Message is a model now rather than a column in chatroom

---

client/components/vidchat.js
public/style.css

Multi video chat working but no channels are implemented yet.

multi user video chat working

---

client/components/GithubProjectBoard.js
public/style.css

added columns for GitHub project board

---

client/components/AddProjectCard.js
client/components/AddProjectCardContainer.js
client/components/GithubProjectBoard.js
client/components/collab.js
client/routes.js
client/store/addProjectCard.js
client/store/index.js
public/style.css
server/api/github.js
server/api/projects.js

Created component for adding card to project board. Adding card on collab page will add to github board and re-render local board to display new entry.
---

Add project card

---

client/components/AllProposals.js
client/components/AllProposalsContainer.js
client/components/index.js
client/routes.js
client/store/allProposals.js
client/store/index.js
script/seed.js
server/api/index.js
server/api/orgs.js
server/api/proposals.js
server/db/models/proposal.js

Added the AllProposals component and dummy data

---

client/components/SingleProposal.js
client/store/singleProposal.js
testing.md

testing readme

---

client/components/AllProposals.js
script/seed.js
server/db/models/proposal.js

Also added images to seed file - please reseed once you pull from master
---

styling for all proposals page

---

client/components/OrganizationHome.js
client/components/OrganizationHomeContainer.js
client/components/OrganizationProposal.js
client/components/OrganizationProposalContainer.js
client/components/navbar.js
client/routes.js
client/store/proposal.js
server/api/orgs.js

Can create posts for specific orgs now. Also added view proposal button to navbar

Added create proposal page

---

client/components/SingleProposal.js
client/components/SingleProposalContainer.js
client/components/index.js
client/routes.js
client/store/singleProposal.js
server/api/proposals.js

Added singleProposal component

---

client/components/GithubFeed.js
client/components/SingleProposal.js
client/components/SingleProposalContainer.js
client/components/home.js
client/components/navbar.js
client/store/addProjectCard.js
server/api/proposals.js
server/db/models/proposal.js

Added single proposal view

---

client/components/AllProposals.js
client/components/ProjectSignupButton.js
client/store/index.js
client/store/projectSignup.js
server/api/projects.js
server/api/proposals.js
server/db/models/index.js

project and repo creation working, and user being properly associated with project.
Note that there is some unfinished login in the post route for /projects. Next step is to limit project to 4 devs, creating a new project and new repo when limit is hit.
---

Project signup

---

client/components/EditOrganization.js
client/components/EditOrganizationContainer.js
client/components/OrganizationHome.js
client/components/index.js
client/routes.js
client/store/organization.js
server/api/orgs.js
server/db/models/organization.js

Can edit organization details. Has a default imageURL. Will need to put validation later.

added edit organization component and functionality

---

client/components/AllProposals.js
client/components/SingleProposal.js
script/seed.js
server/api/proposals.js
server/db/models/proposal.js

Eager Loading to include organizations in proposals

---

client/app.js
client/components/LandingPage.js
client/components/LandingPageContainer.js
client/components/footer.js
client/components/index.js
client/routes.js
public/style.css

Added landing page styling

---

client/components/OrganizationProposal.js
client/components/OrganizationProposalContainer.js
client/store/cause.js
client/store/index.js
script/seed.js
server/api/causes.js
server/api/index.js
server/api/orgs.js

Re-seed the database! There are some placeholder causes

can assign causes to proposal now

---

client/components/Project.js
client/components/ProjectContainer.js
client/components/ProjectSignupButton.js
client/components/userProfile.js
client/components/userProfileContainer.js

clicking project from user profile page routes to /project/:projectId and /project/:projectId renders the correct project from db.
---

fixed routing from user profile to project page

---

client/components/AddProjectCard.js
client/components/GithubProjectBoard.js
client/components/Project.js
client/components/utils/GitHubUtils.js
public/style.css

some styling for project page

---

client/components/EditProfile.js
client/components/EditProfileContainer.js
client/components/auth-form.js
client/routes.js
client/store/user.js

Ignore anything to do with edit profile for now

fixes to more buttons--ignore the editProfile components--in progress

---

client/components/chatbox.js
client/components/chatboxContainer.js
client/store/chatbox.js
client/store/project.js
script/seed.js
server/api/users.js
server/db/models/index.js

each project has its own channel chat and chat box renders messages based on channel

---

script/seed.js

Please re-seed. There shouldn't be anymore problems with getting the project page to render. If you run into any, let me know.

added all projects and repos to seed

---

server/api/projects.js

Edited the project post route to find or create a chatroom now.

making a project now finds or creates a chatroom

---

client/app.js
client/components/GithubProjectBoard.js
public/style.css

Footer is now sticky! Also, the chatbox doesn't disappear when in the same position as the footer.

sticky footer and chatbox over footer

---

client/components/EditOrganization.js
client/components/EditProfile.js
client/components/EditProposals.js
client/components/OrganizationProposal.js
client/components/SingleProposal.js
client/components/auth-form.js

Some fields are required now to sign up and to edit pages

Added requirements to form fields

---

client/components/chatboxNav.js
public/style.css

chatboxnav is smaller when not open

---

client/components/GithubProjectBoard.js
client/components/LandingPage.js
client/components/chatboxNav.js
public/index.html
public/style.css

Styling tweaks

---

client/components/footer.js
public/index.html
public/style.css

Centered and added an inspirational quote.

Added to footer

---

client/components/LandingPage.js
client/components/SingleProposal.js
client/components/about.js
client/components/footer.js
client/components/index.js
client/routes.js
public/style.css
server/api/utils.js

Added about us page

---

client/components/GithubProjectBoard.js

slight refactoring for projectboard component

slight refactoring for projectboard component

---

client/app.js
client/components/navbar.js
public/style.css

fixed projectboard card dragging mystery!

Projectboard dragging

---

client/components/ProjectSignupButton.js
client/components/auth-form.js
client/components/userProfile.js
client/store/user.js
public/style.css
script/seed.js
server/api/users.js
server/db/models/user.js

Added firstname/lastname to db, signup page, and seed (please re-seed!).
Added some styling to user profile page.

User profile styling

---

client/components/auth-form.js
public/style.css
server/auth/github.js

styling for signup/login pages

styling for signup/login pages

---

client/components/OrganizationProposal.js
script/seed.js

Seed user updates

---

client/components/OrganizationProposal.js

Styling updates on create proposal page

---

client/app.js
client/components/chatbox.js
client/components/chatboxNav.js
client/components/vidchat.js
client/store/fetchProjectForToast.js
client/store/index.js
package-lock.json
package.json
public/style.css

Npm install! Alert is gone from closing video chat and you now receive notifications for new messages for projects you are associated with.

removed alert from vid chat and added toast notifications 

---

client/components/AllProposals.js
client/components/LandingPage.js
client/components/OrganizationHome.js
client/components/OrganizationHomeContainer.js
client/components/auth-form.js
client/components/userProfile.js
public/style.css
server/api/orgs.js
server/db/models/organization.js

proposals rendering on org profile page

Org profile styling

---

client/components/GithubFeed.js
client/components/Project.js
package-lock.json
public/style.css

Project collab page styling

---

client/components/GithubFeed.js
client/components/GithubFeedContainer.js
client/components/ProjectSignupButton.js
client/components/SingleProposal.js
public/style.css

Exterminating

---

script/seed.js

Seed update
